package com.eventuality.pages;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navHome = new javax.swing.JButton();
        navSignIn = new javax.swing.JButton();
        lblWlcome = new javax.swing.JLabel();
        lblGallery = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblWlcome1 = new javax.swing.JLabel();
        lblWlcome2 = new javax.swing.JLabel();
        lblWlcome3 = new javax.swing.JLabel();
        lblWlcome4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        navHome.setBackground(new java.awt.Color(102, 153, 255));
        navHome.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        navHome.setForeground(new java.awt.Color(0, 0, 0));
        navHome.setText("HOME");
        navHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        getContentPane().add(navHome);
        navHome.setBounds(660, 20, 135, 30);
        navHome.getAccessibleContext().setAccessibleName("");

        navSignIn.setBackground(new java.awt.Color(102, 153, 255));
        navSignIn.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        navSignIn.setForeground(new java.awt.Color(0, 0, 0));
        navSignIn.setText("SIGN IN");
        navSignIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        navSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSignInActionPerformed(evt);
            }
        });
        getContentPane().add(navSignIn);
        navSignIn.setBounds(810, 20, 135, 30);
        navSignIn.getAccessibleContext().setAccessibleName("");

        lblWlcome.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        lblWlcome.setForeground(new java.awt.Color(51, 0, 51));
        lblWlcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcome.setText(" Eventuality is the start to a more fun and interactive student life turning inspiring ideas into Eventual Reality.");
        getContentPane().add(lblWlcome);
        lblWlcome.setBounds(50, 240, 870, 40);
        lblWlcome.getAccessibleContext().setAccessibleName("");

        lblGallery.setBackground(new java.awt.Color(102, 153, 255));
        lblGallery.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        lblGallery.setForeground(new java.awt.Color(0, 0, 0));
        lblGallery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGallery.setText("GALLERY");
        lblGallery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGallery.setOpaque(true);
        lblGallery.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblGallery);
        lblGallery.setBounds(10, 300, 940, 40);
        lblGallery.getAccessibleContext().setAccessibleName("");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 80, 940, 10);

        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 10, 390, 60);

        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("img");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(770, 370, 180, 120);

        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("img");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 370, 180, 120);

        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("img");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 370, 180, 120);

        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("img");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(520, 370, 180, 120);

        lblWlcome1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        lblWlcome1.setForeground(new java.awt.Color(51, 0, 51));
        lblWlcome1.setText("WELCOME TO EVENTUALITY");
        getContentPane().add(lblWlcome1);
        lblWlcome1.setBounds(360, 90, 240, 60);

        lblWlcome2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        lblWlcome2.setForeground(new java.awt.Color(51, 0, 51));
        lblWlcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcome2.setText("A simple platform in which students can express their creative and intellectual experiences through on and off campus");
        getContentPane().add(lblWlcome2);
        lblWlcome2.setBounds(20, 140, 920, 40);

        lblWlcome3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        lblWlcome3.setForeground(new java.awt.Color(51, 0, 51));
        lblWlcome3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcome3.setText("held events. This platform serves as networking opportunities for students within their respective fields of study");
        getContentPane().add(lblWlcome3);
        lblWlcome3.setBounds(50, 170, 880, 40);

        lblWlcome4.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        lblWlcome4.setForeground(new java.awt.Color(51, 0, 51));
        lblWlcome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcome4.setText(" by expanding campus experiences with peers and their interests in and around CPUT campuses.");
        getContentPane().add(lblWlcome4);
        lblWlcome4.setBounds(50, 200, 870, 40);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSignInActionPerformed

        this.setVisible(false);
        new Login().setVisible(true);

    }//GEN-LAST:event_navSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGallery;
    private javax.swing.JLabel lblWlcome;
    private javax.swing.JLabel lblWlcome1;
    private javax.swing.JLabel lblWlcome2;
    private javax.swing.JLabel lblWlcome3;
    private javax.swing.JLabel lblWlcome4;
    private javax.swing.JButton navHome;
    private javax.swing.JButton navSignIn;
    // End of variables declaration//GEN-END:variables
}
