package com.eventuality.pages;

public class Student_Live_Events extends javax.swing.JFrame {

    /**
     * Creates new form Student_Live_Events
     */
    public Student_Live_Events() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabStudent = new javax.swing.JTabbedPane();
        pnlLiveEvents = new javax.swing.JPanel();
        lblLive = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        pnlMyEvents = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        txtdscription = new javax.swing.JTextField();
        cbxCategory = new javax.swing.JComboBox<>();
        jCalender = new com.toedter.calendar.JDateChooser();
        cbxSTime = new javax.swing.JComboBox<>();
        cbxETime = new javax.swing.JComboBox<>();
        cbxDNTime = new javax.swing.JComboBox<>();
        cbxNDTime = new javax.swing.JComboBox<>();
        cbxCampus = new javax.swing.JComboBox<>();
        cbxCapacity = new javax.swing.JComboBox<>();
        txtStudentNo = new javax.swing.JTextField();
        cbxVolunteer = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        pnlBookedE = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblBooked = new javax.swing.JLabel();
        lblApprove = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();
        lblEvent = new javax.swing.JLabel();
        btnRedo = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        jspVolunteer = new javax.swing.JScrollPane();
        txtVolunteer = new javax.swing.JTextArea();
        navHome = new javax.swing.JButton();
        navGallery = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLive.setText("Live Events");

        lblDetails.setText("Events Details");

        btnBook.setText("Book Event");

        javax.swing.GroupLayout pnlLiveEventsLayout = new javax.swing.GroupLayout(pnlLiveEvents);
        pnlLiveEvents.setLayout(pnlLiveEventsLayout);
        pnlLiveEventsLayout.setHorizontalGroup(
            pnlLiveEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLiveEventsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblLive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addGroup(pnlLiveEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBook)
                    .addComponent(lblDetails))
                .addGap(150, 150, 150))
        );
        pnlLiveEventsLayout.setVerticalGroup(
            pnlLiveEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLiveEventsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlLiveEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLive)
                    .addComponent(lblDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(btnBook)
                .addGap(93, 93, 93))
        );

        tabStudent.addTab("Live Events", pnlLiveEvents);

        txtTitle.setText("title");
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        txtdscription.setText("Description");
        txtdscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdscriptionActionPerformed(evt);
            }
        });

        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "category", "Item 2", "Item 3", "Item 4" }));

        cbxSTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxETime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxDNTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxNDTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxCapacity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtStudentNo.setText("jTextField3");

        cbxVolunteer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegister.setText("Register Staff");

        btnApprove.setText("Request Approval");

        pnlBookedE.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitle.setText("No Events Created");

        lblBooked.setText("Booked Events");

        lblApprove.setText("jLabel1");

        javax.swing.GroupLayout pnlBookedELayout = new javax.swing.GroupLayout(pnlBookedE);
        pnlBookedE.setLayout(pnlBookedELayout);
        pnlBookedELayout.setHorizontalGroup(
            pnlBookedELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookedELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookedELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookedELayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblApprove)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookedELayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblBooked)
                        .addGap(245, 245, 245))))
        );
        pnlBookedELayout.setVerticalGroup(
            pnlBookedELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookedELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookedELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblApprove))
                .addGap(81, 81, 81)
                .addComponent(lblBooked)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        lblCreate.setText("Create Event");

        lblEvent.setText("My Events");

        btnRedo.setText("Re-Create Event");

        btnStatus.setText("Check Event Status");

        txtVolunteer.setColumns(20);
        txtVolunteer.setRows(5);
        jspVolunteer.setViewportView(txtVolunteer);

        javax.swing.GroupLayout pnlMyEventsLayout = new javax.swing.GroupLayout(pnlMyEvents);
        pnlMyEvents.setLayout(pnlMyEventsLayout);
        pnlMyEventsLayout.setHorizontalGroup(
            pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyEventsLayout.createSequentialGroup()
                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMyEventsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMyEventsLayout.createSequentialGroup()
                                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMyEventsLayout.createSequentialGroup()
                                        .addComponent(cbxSTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxDNTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtdscription, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCreate)
                                    .addGroup(pnlMyEventsLayout.createSequentialGroup()
                                        .addComponent(cbxETime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxNDTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cbxCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMyEventsLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jspVolunteer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlMyEventsLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnRegister))
                    .addGroup(pnlMyEventsLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnApprove)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBookedE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyEventsLayout.createSequentialGroup()
                        .addComponent(lblEvent)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyEventsLayout.createSequentialGroup()
                        .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRedo)
                            .addComponent(btnStatus))
                        .addContainerGap())))
        );
        pnlMyEventsLayout.setVerticalGroup(
            pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyEventsLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBookedE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRedo)
                .addGap(18, 18, 18)
                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStatus)
                    .addComponent(btnApprove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMyEventsLayout.createSequentialGroup()
                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMyEventsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyEventsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCreate)
                        .addGap(33, 33, 33)))
                .addComponent(txtdscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxETime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDNTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNDTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlMyEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        tabStudent.addTab("My Events", pnlMyEvents);

        navHome.setText("HOME");

        navGallery.setText("GALLERY");

        btnSignOut.setText("SIGN OUT");

        lblLogo.setText("LOGO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(navHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(navGallery)
                        .addGap(14, 14, 14)
                        .addComponent(btnSignOut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignOut)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(navHome)
                        .addComponent(lblLogo)
                        .addComponent(navGallery)))
                .addGap(15, 15, 15)
                .addComponent(tabStudent)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdscriptionActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Live_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Live_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Live_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Live_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Live_Events().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnStatus;
    private javax.swing.JComboBox<String> cbxCampus;
    private javax.swing.JComboBox<String> cbxCapacity;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxDNTime;
    private javax.swing.JComboBox<String> cbxETime;
    private javax.swing.JComboBox<String> cbxNDTime;
    private javax.swing.JComboBox<String> cbxSTime;
    private javax.swing.JComboBox<String> cbxVolunteer;
    private com.toedter.calendar.JDateChooser jCalender;
    private javax.swing.JScrollPane jspVolunteer;
    private javax.swing.JLabel lblApprove;
    private javax.swing.JLabel lblBooked;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblLive;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton navGallery;
    private javax.swing.JButton navHome;
    private javax.swing.JPanel pnlBookedE;
    private javax.swing.JPanel pnlLiveEvents;
    private javax.swing.JPanel pnlMyEvents;
    private javax.swing.JTabbedPane tabStudent;
    private javax.swing.JTextField txtStudentNo;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextArea txtVolunteer;
    private javax.swing.JTextField txtdscription;
    // End of variables declaration//GEN-END:variables
}
